version: "3.8"
services:
  localstack:
    image: localstack/localstack:2.0.2
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,iam
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
