apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
  labels:
    app: events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: events:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
