apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets
  labels:
    app: tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: tickets:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
