replicaCount: 3
maxUnavailable: 0
maxSurge: 1
image:
  repository: users
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi